name: Custom Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  custom_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "Hello, this is a custom workflow!"

      - name: Make script executable
        run: chmod +x ./custom_script.sh
  
      - name: Run a custom script
        run: ./customscript.sh